### ISSUE TITLE
UI not showing Area stored in Popit

### ISSUE THREAD

**Issue by kaerumy** [Sinar/sinar_popit_ui#19]
/posts/edit/5365e37f19ee29270d8a9f36

https://sinar-malaysia.popit.mysociety.org/api/v0.1/posts/5365e37f19ee29270d8a9f36

```
"area": {
      "state": "Penang",
      "id": "P49",
      "name": "Tanjong"
    },
```

![image](https://cloud.githubusercontent.com/assets/1060743/8743524/30c10ce2-2ca2-11e5-8e24-15839f600f40.png)

**Comment by sweemeng** [comment]
Fixed, keep standard way to store area
